-- Start of DDL Script for Procedure BOJBSV.CALCULATE_COSTPRICE
-- Generated 24-Jan-2024 15:57:15 from BOJBSV@DB_11


CREATE OR REPLACE 
PROCEDURE calculate_costprice (PV_SEACCTNO VARCHAR2, PV_BUYQTTY NUMBER, PV_BUYPRICE NUMBER,PV_SECUREDRATIO NUMBER,PV_ISMATCH VARCHAR2 DEFAULT 'Y')
   IS
--
-- PURPOSE: DIEU CHINH GIA VON THEO LENH KHOP MUA CHUNG KHOAN
--
-- ---------   ------  -------------------------------------------
    V_CURRDATE          DATE;
    V_TRADEQTTY         NUMBER;
    V_AMOUNT            NUMBER;
     V_TRANFERQTTY          NUMBER := 0;
     V_TRANFERVALUE     NUMBER := 0;
    V_COSTPRICE         NUMBER;
     V_BEGINCOSTPRICE       NUMBER := 0;
BEGIN
     /*
     --lay thong tin so luong chuyen cho ve trong ngay
     BEGIN
        SELECT NVL(SUM(NVL(QTTY,0)),0) QTTY,NVL(SUM(NVL(QTTY*A.COSTPRICE,0)),0) AMOUNT
        INTO V_TRANFERQTTY,V_TRANFERVALUE FROM SETRANFERSERC A
        WHERE A.SERECACCTNO = PV_SEACCTNO AND STATUS = 'N'
        AND A.TXDATE = (SELECT TO_DATE(VARVALUE,'DD/MM/YYYY') FROM SYSVAR WHERE VARNAME = 'CURRDATE');
     EXCEPTION WHEN OTHERS THEN
        V_TRANFERQTTY := 0;
        V_TRANFERVALUE := 0;
     END;
     */

    -- LAY THONG TIN NGAY GIAO DICH KE TIEP
    BEGIN
        --SELECT TO_DATE(VARVALUE, 'DD/MM/YYYY') INTO V_CURRDATE FROM SYSVAR WHERE GRNAME = 'SYSTEM' AND VARNAME = 'CURRDATE' AND ROWNUM = 1;
        SELECT NVL(SUM(SE.TRADE+SE.T0+SE.T1+SE.T2 +  SE.PENDINGQTTY + SE.CAQTTT_WATING ),0) TRADE, NVL(SUM((SE.TRADE+SE.T0+SE.T1+SE.T2 +  SE.PENDINGQTTY+ SE.CAQTTT_WATING)*SE.COSTPRICE),0) AMOUNT
        INTO V_TRADEQTTY, V_AMOUNT
        FROM SEMAST SE WHERE  SE.ACCTNO = PV_SEACCTNO;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            V_TRADEQTTY := 0;
            V_AMOUNT := 0;
    END;



    IF NVL(V_TRADEQTTY,0) + NVL(PV_BUYQTTY,0) > 0 THEN
          V_COSTPRICE := ROUND((nvl(V_AMOUNT,0) + ((PV_BUYQTTY * PV_BUYPRICE) * PV_SECUREDRATIO /100))/ (V_TRADEQTTY + PV_BUYQTTY));
    ELSE
          V_COSTPRICE := 0;
    END IF;

     IF NVL(PV_ISMATCH,'Y') = 'N' THEN

        IF((NVL(V_TRADEQTTY,0) + NVL(PV_BUYQTTY,0))>0) THEN
          V_BEGINCOSTPRICE := ROUND((NVL(V_AMOUNT,0) + ((PV_BUYQTTY * PV_BUYPRICE) * PV_SECUREDRATIO /100))/ (V_TRADEQTTY + PV_BUYQTTY));

          UPDATE SEMAST SET COSTPRICE = V_COSTPRICE,BEGIN_COSTPRICE = V_BEGINCOSTPRICE  WHERE ACCTNO = PV_SEACCTNO ;
        END IF ;

     ELSE
          UPDATE SEMAST SET COSTPRICE = V_COSTPRICE  WHERE ACCTNO = PV_SEACCTNO ;
     END IF;




    /*-- LUU LICH SU CAP NHAT GIA VON
    INSERT INTO SECOSTPRICE (AUTOID, ACCTNO, TXDATE, COSTPRICE, PREVCOSTPRICE, DCRAMT, DCRQTTY, DELTD)
    SELECT SEQ_SECOSTPRICE.NEXTVAL, ACCTNO, V_NEXTDATE,
        ROUND((PREVQTTY * COSTPRICE + PV_BUYQTTY * PV_BUYPRICE) / (PREVQTTY + PV_BUYQTTY), 4), ROUND(COSTPRICE, 4),
        (PV_BUYQTTY * PV_BUYPRICE), PV_BUYQTTY, 'N'
    FROM SEMAST WHERE STATUS = 'A' AND ACCTNO = PV_SEACCTNO;

    -- CAP NHAT GIA VON
    UPDATE SEMAST SET
        PREVQTTY =  ((PREVQTTY + ABS(PREVQTTY))/2)  + PV_BUYQTTY,
        COSTPRICE = ROUND((((PREVQTTY + ABS(PREVQTTY))/2)  * COSTPRICE + PV_BUYQTTY * PV_BUYPRICE) / (((PREVQTTY + ABS(PREVQTTY))/2) + PV_BUYQTTY), 4),
        COSTDT = V_NEXTDATE
    WHERE STATUS = 'A' AND ACCTNO = PV_SEACCTNO;*/
EXCEPTION
    WHEN OTHERS THEN
    PKG_LOG.LOGMSG(' TRACE:' ||  SUBSTR(DBMS_UTILITY.FORMAT_ERROR_BACKTRACE ,0,500) || ' CODE:'    ||SQLCODE  || ' SQLERRM:' ||SUBSTR(SQLERRM,1,500)) ;

        RETURN;
END; -- PROCEDURE
/



-- End of DDL Script for Procedure BOJBSV.CALCULATE_COSTPRICE

